FROM golang:1.14 as builder

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
  && apt-get install -y build-essential libc6-dev

ENV GOPROXY=https://goproxy.io,direct

COPY . /opt/
WORKDIR /opt

RUN cd /opt \
  && ls -alh \
  && make build-static2

# FROM kayuii/chia-plotter:chia-v1.1.7
# COPY --from=builder /opt/chiacli-static /root/chiacli
